### ISSUE TITLE
Error: RPC Server is unavailable

### ISSUE THREAD

**Issue by akilanmaris** [Microsoft/WindowsProtocolTestSuites#107] opened 2017-04-04 11:55 UTC
When I'm running the  .\Config-Client.ps1, I'm getting the following error message.

**Get-WmiObject : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5142.0\Scripts\Config-Client.ps1:167 char:19
+ ... Version =  (Get-WmiObject -comp "SUT01" -Credential $Credential -clas ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

You cannot call a method on a null-valued expression.
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5142.0\Scripts\Config-Client.ps1:168 char:1
+ $FirstDotIndex = $SUTOSVersion.IndexOf('.')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5142.0\Scripts\Config-Client.ps1:169 char:1
+ $SecondDotIndex = $SUTOSVersion.IndexOf('.', $FirstDotIndex+1)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5142.0\Scripts\Config-Client.ps1:176 char:2
+     $SUTOsVersion = $SUTOsVersion.substring(0,$SecondDotIndex)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull**

 I have disabled the firewall on both the SUT and driver computer already.

**Comment by yazeng** [comment] 2017-04-05 06:05
Thanks for contacting us.
Could you confirm if the computer name of SUT is "SUT01"?
And if you can ping "SUT01" from driver successfully?

Thanks,
Yan

**Comment by akilanmaris** [comment] 2017-04-05 06:42
Hi Yan,

Thanks for a really quick response.

The computer name of SUT is not "SUT01". However, I have set the "serverComputerName" attribute correctly in the ParamConfig.xml file on both the SUT and driver computer.

I'm able to ping the SUT using it's computer name from driver computer successfully.

Regards,
Akilan

**Comment by yazeng** [comment] 2017-04-05 06:50
Hi Akilan,
Unfortunately, "SUT01" is hardcoded in the script...
You may want to modify the script manually and rerun it.
And meanwhile I'll file a bug on this and see what we can do in the future.

Thanks,
Yan

**Comment by akilanmaris** [comment] 2017-04-05 06:59
Hi Yan,

So does this mean I can't use the readily available SMB test suite .msi file (https://github.com/Microsoft/WindowsProtocolTestSuites/releases) ?

I should clone the repository, modify the script manually and then build the MS-SMB test suite, right ?

Regards,
Akilan

**Comment by akilanmaris** [comment] 2017-04-05 08:11
Hi Yan,

Can I use a Windows 8.1 or Windows 10 machine as SUT instead of Windows Server 2008 or Windows Server 2012 ?

Regards,
Akilan

**Comment by yazeng** [comment] 2017-04-05 09:07
> So does this mean I can't use the readily available SMB test suite .msi file (https://github.com/Microsoft/WindowsProtocolTestSuites/releases) ?

You can still install the msi file. After the installation, you can modify the script. The script is copied 
here: C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Scripts\

> Can I use a Windows 8.1 or Windows 10 machine as SUT instead of Windows Server 2008 or Windows Server 2012 ?

I do not recommend you to do that. But I think the SUT should be your own server, right? If you just want to check if you can run the test suite, it's OK to use 8.1 or Win 10 as SUT.

**Comment by akilanmaris** [comment] 2017-04-05 09:26
There are several scripts in C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Scripts\
Can you please tell me the script that I should modify ?

**Comment by yazeng** [comment] 2017-04-05 09:29
C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Scripts\Config-Client.ps1,
replace all "SUT01" to your SUT name.

**Comment by akilanmaris** [comment] 2017-04-05 11:45
I was able to run the test after that !

But on running RunAllTestCases from a Windows 8.1 driver against a Windows 2012 R2 SUT, only one test case has passed. 

Summary
-------
Test Run Failed.
  Failed  1215
  Passed     1
  ------------
  Total   1216

I'm surprised to know that these many test cases fail in a Windows environment. 
Am I missing something or doing it wrong ?

**Comment by yazeng** [comment] 2017-04-06 01:13
Congratulations!
Could you copy the error log of the failed test cases from the test result file *.trx?

**Comment by akilanmaris** [comment] 2017-04-06 04:42
Do you want me to upload that entire .trx file ? Or is there any way to get the error log alone ?

**Comment by yazeng** [comment] 2017-04-06 05:00
Either way is OK for me. 
1. Upload the .trx file, if you can not upload it directly, try to zip it or rename it to *.png.
2. The .trx file can be opened by Visual studio, or by text editor (it's simply an XML file), then find the error message and call stack of the failed cases, and copy them here.

**Comment by akilanmaris** [comment] 2017-04-06 08:15
![fapteam_fapteam-win10j 2017-04-05 21_33_58](https://cloud.githubusercontent.com/assets/16002802/24744239/ed603c80-1ace-11e7-8950-7c6eaab48483.png)

I have uploaded the .trx after zipping it and then renaming it to .png.

Actually, I'm trying to run this from a Windows 10 Enterprise N as driver computer and not a Windows 8.1 as mentioned in earlier comments.

**Comment by yazeng** [comment] 2017-04-07 06:40
The log below shows that executing script "ConfigSignState.ps1" failed.
```
2017-04-05 21:38:28.820    [CheckFailed] PowerShell script write error 'ERROR: Access is denied.' At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Batch\TestResults\fapteam_FAPTEAM-WIN10J 2017-04-05 21_33_58\Out\ConfigSignState.ps1:16 char:5
+     cmd /C reg ADD $regeditPath /f /v enablesecuritysignature /t REG_ ...
```
```
    assert  failed: expected 'False', actual 'True' (isSignatureRequired of NonExtendedNegotiateResponse, state S75)
```
The test case calls this script to config the SignState of SUT.
You could run the script separately to see where the issue is.
The script is under this folder:
WindowsProtocolTestSuites\TestSuites\MS-SMB\src\Adapter\ServerSetup\

Thanks,
Yan

**Comment by akilanmaris** [comment] 2017-04-07 07:20
Where should I run the script ? Driver computer or SUT ?

**Comment by yazeng** [comment] 2017-04-07 08:40
Driver.

**Comment by akilanmaris** [comment] 2017-04-07 08:46
If I run that script from the Driver using Powershell, I don't see any errors !

**Comment by yazeng** [comment] 2017-04-07 09:32
Hi Akilan,
Just want to make sure, do you run the script on the driver to change the sign state of SUT and it succeeds? (You can verify it by running the PowerShell command " Get-SmbServerConfiguration" on SUT, and checking if "EnableSecuritySignature" and "RequireSecuritySignature" is changed correctly.)
If so, maybe the privilege of the console which runs the test cases are different with the PowerShell command window, because the error log of test case shows "ERROR: Access is denied.".
Try open the commandline console as administrator first and then run "RunAllTestCases" in that console.

Thanks,
Yan

**Comment by akilanmaris** [comment] 2017-04-07 09:41
Hi Yan,

How am I supposed to run that script on the driver computer ? I just opened a Powershell as administrator and invoked that script. Is that fine ?

After running the script from driver, I checked the SmbServerConfiguration on the SUT. Both "EnableSecuritySignature" and "RequireSecuritySignature" are set to True. 

Regards,
Akilan

**Comment by yazeng** [comment] 2017-04-07 09:49
Aha, you need to modify the script first. Sorry I forgot to mention that.
Modify the "servername" and "signstate" as below:
```
[String]$serverName = "Sut01"  // change to your SUT name
[String]$signState = "Enabled"
```
If the script succeeds, "EnableSecuritySignature" should be true, and "RequireSecuritySignature" be false.

**Comment by akilanmaris** [comment] 2017-04-07 10:21
I'm getting the following error !

PS C:\MicrosoftProtocolTests> .\ConfigSignState.ps1
ERROR: Access is denied.
ERROR: Access is denied.

**Comment by yazeng** [comment] 2017-04-10 02:32
So the error is the same with the log of failed test cases.
The script is to add a key to the registry of SUT. It seems the user you logged on to the driver does not have the privilege to access the registry of SUT remotely. The user should be the administrator of SUT. 
You can either switch to another user which has the admin privilege of SUT, or give the current user admin privilege from SUT.

**Comment by akilanmaris** [comment] 2017-04-10 06:17
I have logged into the driver using a local user on the driver. Is it possible to give that user administrator rights on the SUT ?

**Comment by akilanmaris** [comment] 2017-04-10 07:59
When I tried running the tests after logging in to the driver computer as a AD user with administrator rights on the SUT, all the test cases passed ! :smile: 

So now if I want to run this tool on our own server, what are the changes I should make ? Can you please outline the steps to follow ?

**Comment by akilanmaris** [comment] 2017-04-10 08:19
As mentioned [Here](https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/MS-SMB/docs/MS-SMB_ServerUserGuide.md#7.2.1), should it definitely be only FAT and NTFS disks ? Because, we have our own file system. Will this tool work fine with our server as well ?

**Comment by yazeng** [comment] 2017-04-10 08:43
Congratulations! Glad to hear that. 

Follow the [user guide](https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/MS-SMB/docs/MS-SMB_ServerUserGuide.md#7.2.2) to config your own server.
Then modify ParamConfig.xml accordingly and run Config-Client.ps1 again, to modify the .ptfconfig file of the test suite.

> As mentioned Here, should it definitely be only FAT and NTFS disks ? Because, we have our own file system. Will this tool work fine with our server as well ?

I've answered this question [here](https://github.com/Microsoft/WindowsProtocolTestSuites/issues/105).
I don't know how much difference your server is from Windows. So just run all the cases, and analyze the result afterwards.

**Comment by akilanmaris** [comment] 2017-04-11 06:38
Should I create two folders(for NTFS disk and FAT disk) in a single share point or should I have two share points separately for each ?

**Comment by yazeng** [comment] 2017-04-11 08:52
According to user guide, you should create two folders under the share of NTFS disk, and another two folders under the share of FAT disk.

**Comment by akilanmaris** [comment] 2017-04-11 08:55
Is there any specific name to be given for the shares ?

**Comment by yazeng** [comment] 2017-04-11 09:04
Sorry, if the SUT is windows, the two folders are in the root directory of the volume. It's not under a specific share.
The targeting shares are the four folders. The parent of the four folders is not important. You could create the folders anywhere in your own server, just share it to "Everyone" and grant "Read/Write" permission.
The folders' names are listed in user guide.
One suggestion, you can check the Windows SUT which you just configured by our script, to see what it is like in Windows as reference.

**Comment by akilanmaris** [comment] 2017-04-11 12:37
Okay. I'll try to emulate whatever is present in the Windows SUT.

I have one more question. The test suite has only CLI or does it have an UI as well ?

**Comment by yazeng** [comment] 2017-04-12 02:11
Unfortunately, the answer is no...
We do have a GUI tool (Protocol Test Manager) for other test suites, like SMB2, RDP, etc.
But if you installed Visual Studio in the driver computer, you can use it to run the test cases. (Use "Test Explorer" of Visual Studio).

**Comment by akilanmaris** [comment] 2017-04-12 10:40
I tried running the Config-Client.ps1 after replacing SUT01 in that script with the name of SUT(blr7-100-110). But still, I get the following error.
```
Get-WmiObject : The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Scripts\Config-Client.ps1:167 char:19
+ ... Version =  (Get-WmiObject -comp "blr7-100-110" -Credential $Credentia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], COMException
    + FullyQualifiedErrorId : GetWMICOMException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

You cannot call a method on a null-valued expression.
At C:\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Scripts\Config-Client.ps1:168 char:1
+ $SUTOsVersion = $SUTOsVersion.substring(0,$SUTOsVersion.length-5)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by yazeng** [comment] 2017-04-13 06:44
Hi Akilan,
The error is because the script is trying to get the OS version of your SUT, which is not reasonable if your SUT is not Windows.
I suggest you skip running the script. Just modify the config file below manually:
```
\WindowsProtocolTestSuites\TestSuites\MS-SMB\src\TestSuite\MS-SMB_ServerTestSuite.deployment.ptfconfig
```
After the modification, copy it to the folder below, and then you can try to run the test cases.
```
\MicrosoftProtocolTests\MS-SMB\Server-Endpoint\1.0.5000.0\Bin\
```

Thanks, 
Yan

**Comment by akilanmaris** [comment] 2017-04-17 11:49
Hi Yan,

I will try it out and let you know.

Regards,
Akilan

**Comment by akilanmaris** [comment] 2017-04-25 13:09
Hi Yan,

In that MS-SMB_ServerTestSuite.deployment.ptfconfig file, what do the various implementations such as R4Implementation and R105227Implementation mean ?

Regards,
Akilan

**Comment by yazeng** [comment] 2017-04-26 09:20
Hi Akilan,
They mean if the specified requirements are covered in test suite.
The requirement spec was not upload to GitHub, which is a bug.
I uploaded it here. You can unzip it and take a look. 
For example, for R4Implementation, you should search "R4" in the excel file.
[MS-SMB_ServerRequirementSpec.zip](https://github.com/Microsoft/WindowsProtocolTestSuites/files/957800/MS-SMB_ServerRequirementSpec.zip)

Thanks,
Yan

**Comment by akilanmaris** [comment] 2017-04-26 09:50
Hi Yan,

Thanks for sharing the excel file. Also what does TDI/Q mean ?

Regards,
Akilan

**Comment by yazeng** [comment] 2017-04-26 10:02
Those are the old configuration items, we'll remove them later. Thank you for reporting the issue!

**Comment by akilanmaris** [comment] 2017-04-26 10:20
So shall I comment out the TDI/Q Fix Section ?

**Comment by yazeng** [comment] 2017-04-27 01:56
Yes, commenting them is a workaround for now.

**Comment by chenlu0616** [comment] 2018-01-03 07:14
Close this issue since no update for a long time. Feel free to reopen it if there is any other questions.

**Closed by chenlu0616** 2018-01-03 07:14 UTC
Labels: MS-SMB
