### ISSUE TITLE
Service principal name is wrongly determined by reverse DNS lookup

### ISSUE THREAD

**Issue by slupu-infinidat** [microsoft/WindowsProtocolTestSuites#233] opened 2020-06-10 10:19 UTC
When supplying a host name (not an ip address) for SutComputerName, the service principal name is determined using a DNS lookup. If this fails, the service principal name is not initialized, and as a result all Kerberos tests fail (without a proper error message).
This DNS lookup relies on a reverse DNS lookup and assumes the SutComputerName to be fully qualified in the domain.
So, firstly, the SutComputerName should not be assumed to be as such, but rather suffixed with the FQDN if needed (or at least validated to be suffixed with the FQDN).
This should determine the service principal name (prefix with 'cifs/') and no DNS lookup is required.

Reverse DNS lookup is not necessarily configured and multiple host names may point to the same ip address, specifically in Active Directory testing environments.
Also, please bear in mind that, as far as we understand, 'net use' does not require reverse DNS lookup.
This issue is located at Smb2Utility.GetCifsServicePrincipalName.

**Comment by yazeng** [comment] 2020-06-12 02:31
Hi Shahar,

Thanks for reporting the issue. The reason we use DNS lookup is to get the FQDN of the SUT, since SutComputerName is basically not an FQDN.
If your server does not support reverse DNS lookup, I can modify the code to use "cifs/" + SutComputerName to make a servicePrincipalName.
Does it work for you?
Attached a possible fix for your reference. It’s in KerberosAuthentication.cs
 
![image](https://user-images.githubusercontent.com/10937464/84458527-c5fdb880-ac97-11ea-8cb2-83909151f217.png)


Best Regards, 
Yan
Windows Protocol Test Suites Development Team

**Comment by slupu-infinidat** [comment] 2020-06-15 07:05
Hi Yan,
Thanks for your response.
This should solve the issue.

**Comment by yazeng** [comment] 2020-06-17 07:56
Hi Shahar,
The issue is fixed in commit ef4f173 and merged into staging.
You can clone the code, build a new version and have a try.

Best Regards, 
Yan
Windows Protocol Test Suites Development Team

**Comment by slupu-infinidat** [comment] 2020-06-22 07:20
Thank you very much, Yan.

**Closed** 2020-07-02 03:30 UTC
Labels: FileServer
