### ISSUE TITLE
Test case failed on Windows SMB3 share

### ISSUE THREAD

**Issue by harshivs** [microsoft/WindowsProtocolTestSuites#218] opened 2020-02-14 12:31 UTC
We have observed a test case failing on a Windows SMB3 share running on Windows Server 2016  when the SMB server is configured with the following settings:
![a7](https://user-images.githubusercontent.com/59079257/74531533-e79d9c00-4f52-11ea-9f2e-0012f4e088a3.png)

The Protocol Test Suite has the following configurations
![a5](https://user-images.githubusercontent.com/59079257/74531720-790d0e00-4f53-11ea-9eba-9373649f631f.png)
![a6](https://user-images.githubusercontent.com/59079257/74531725-7c07fe80-4f53-11ea-8081-f79dfc53004e.png)

Running the Test Case BVT_SessionMgmt_ReconnectSessionSetup with the following output:
![a1](https://user-images.githubusercontent.com/59079257/74531840-c4272100-4f53-11ea-9f47-72e68e9c3967.png)
![a2](https://user-images.githubusercontent.com/59079257/74531842-c5584e00-4f53-11ea-9511-006bc8e3fa18.png)
![a3](https://user-images.githubusercontent.com/59079257/74531844-c6897b00-4f53-11ea-904f-a997289790ac.png)
![a4](https://user-images.githubusercontent.com/59079257/74531847-c7221180-4f53-11ea-959a-e500a31a3cff.png)

**Comment by yazeng** [comment] 2020-02-17 09:35
Hi Harshivs,
Thank you for reporting this issue. 
The root case is that the test suite did not send Encryption Context along with the Negotiate Request when “EncryptData” is set to true on server.
We will fix this and notify you in this thread when the fix is pushed to staging branch.
 
Best Regards,
Yan
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment] 2020-03-11 03:33
Hi Harshivs,
The issue is fixied in commit 52d296f and merged into staging.
 
Best Regards,
Yan
Windows Protocol Test Suites Development Team

**Comment by yazeng** [comment] 2020-03-30 07:26
Hi Harshivs,
Since this thread has been inactive for a long time, we close it for now. Feel free to reopen it if the problem remains.
Windows Protocol Test Suites Development Team

**Closed by yazeng** 2020-03-30 07:26 UTC
Labels: FileServer, bug
