### ISSUE TITLE
Default returnedStatus can erroneously make some tests to pass

### ISSUE THREAD

**Issue by rluo19** [microsoft/WindowsProtocolTestSuites#234] opened 2020-07-29 04:31 UTC
In the FileServer test suite, for example, ReadFileTestCaseS0 expects INVALID_PARAMETER, however the default returnedStatus of ReadFile is INVALID_PARAMETER itself. If ReadFile throws some exception, say timed out, it will return the default and make this test to pass.

IMO a lot of stuff in the adapters should be corrected to use some specific default returnedStatus, such as INTERNAL_ERROR or SERVER_FAULT or anything else at all that at least wouldn't be expected by the tests.

**Comment by huiren-jiang** [comment] 2020-07-29 06:33
Hi rluo19,

Thanks for your suggestion. Just as you found, using default value with specific meaning as return status will make some test cases pass unexpectedly.

We will try to remove unnecessary default value used and run regression test afterwards. When change is committed, we will notify you in this thread.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by huiren-jiang** [comment] 2020-08-21 08:39
Hi rluo19,

The issue is fixed by commit f8a8ba2c505d9fdee8966a2433460d8e259d4f9a.

Best Regards,

Windows Protocol Test Suites Development Team

***
⭐⭐Join us at SNIA SDC SMB IO Lab 2020 (9/21-9/23): https://interopevents.com/sniaonline2020

**Comment by yazeng** [comment] 2020-10-12 01:44
Close it since it's not active for a long time.

**Closed by yazeng** 2020-10-12 01:44 UTC
