### ISSUE TITLE
[MS-RDPEGFX] RDPEGFX_H264Codec_PositiveTest_AVC444v2 failure

### ISSUE THREAD

**Issue by nfedera** [microsoft/WindowsProtocolTestSuites#229] opened 2020-03-04 16:28 UTC
With SUT display verification enabled, the AVC444v2 test failed with xfreerdp.

Here is the original image: ([OriginalPic_Large_1.png](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/H264TestData/BaseImage/OriginalPic_Large_1.png))
![OriginalPic_Large_1](https://user-images.githubusercontent.com/670606/75899387-be7a7800-5e3b-11ea-89a9-dc631639d437.png)

This is what xfreerdp decoded:
![avc444v2_freerdp_1](https://user-images.githubusercontent.com/670606/75899786-4496be80-5e3c-11ea-8f6e-0543133f2422.png)

However, when connecting with mstsc (10.0.18362) to the test suite driver server process, the same data is displayed:
![avc444v2_mstsc_1](https://user-images.githubusercontent.com/670606/75900062-a48d6500-5e3c-11ea-877a-1619846f530c.png)

I assume that the AVC420EncodedBitstream blobs in https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/H264TestData/RDPEGFX_H264Codec_PositiveTest_AVC444v2.xml might be wrong since xfreerdp seems to process AVC444v2 data perfectly fine in real life.

**Comment by sweeetday** [comment] 2020-03-06 07:37
Hi Norbert,

Thanks for your reporting this issue. 

We have started to look into this issue. And will update you with our investigation result in this thread.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by sweeetday** [comment] 2020-03-23 09:46
Hi, Norbert, 
I have tried to repro your scenarios with FreeRDP and latest released Ubuntu 19.10. However, the FreeRDP shows black screen during setup the EGFX connection with Windows driver computer during test cases run.  The test case does not get the message RDPGFX_CAPS_ADVERTISE from FreeRDP and waits till timeout finally. 

The command used in the Java and Python SUTControlAgent  for remote session setup is: xfreerdp /t:RDPSession /f /rfx /gfx /vc:drdynvc,rdpdr /cert-ignore /u:administrator /p:Password01! /v:192.168.101.101:3389

FreeRDP version in my Ubuntu is: 2.0.0-dev5 (2693389a+debian)

May I know which FreeRDP version are you using? Would you please share your repro steps with me so I can follow up debugging this issue?

Thanks.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by nfedera** [comment] 2020-03-23 13:36
Hi Vivian,
Actually this is not directly related to FreeRDP.
Just use a Windows 10 SUT with SUT display verification enabled and, the AVC444v2 test should fail.

You don't even need a remote SUT, if you have a Windows 10 driver PC you can simply enable the interactive adapters and manually connect to localhost via mstsc to see the issue.

I've attached a screen recording demonstrating this here: [mstsc-avc444v2-issue.zip](https://github.com/microsoft/WindowsProtocolTestSuites/files/4369668/mstsc-avc444v2-issue.zip)

**Comment by nfedera** [comment] 2020-03-25 16:56
@sweeetday Just look at e.g. the first two AVC420EncodedBitstream blobs in
in line 35 and 51 of [RDPEGFX_H264Codec_PositiveTest_AVC444v2.xml](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/H264TestData/RDPEGFX_H264Codec_PositiveTest_AVC444v2.xml) and compare them to the first two [RDPEGFX_H264Codec_PositiveTest_AVC444_YUV420Chroma420Together_MainProfile_LargeSize.xml](https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/src/TestSuite/RDPEGFX/H264TestData/RDPEGFX_H264Codec_PositiveTest_AVC444_YUV420Chroma420Together_MainProfile_LargeSize.xml).

You can see that the encoded chroma frame data in the AVC444V2 xml is 100% identical to the blob in the AVC444 xml. This can't be correct. Looks like a copy & paste error.

**Comment by sweeetday** [comment] 2020-04-03 07:14
Hi, Norbert
I have reproduced the issues follow your introduction in my environment. It looks like a test data generation issue.
We still need more time to investigate the root cause. If there’s any progress and fix, I will update you in this thread.
Thanks for your patience.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by sweeetday** [comment] 2020-04-28 01:02
Hi, Norbert
With investigation, we confirm this is a test data issue. We fixed the issue by generating new test data with updated algorithms and source pictures. The new pictures and xml test data were submitted by the commit 2bbf519.

Please have another try with the latest test data and let me know your progress.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by nfedera** [comment] 2020-04-28 10:05
Hi Vivian,

Great, thanks! However I see two issues:

The new source pictures did not get deployed. - a fix is in PR #231 

And I get very low assess values for Cb anc Cr components.
In order for the SUT display verification to succeed I had to lower the threshold to 90%.

Original pic:
![image](https://user-images.githubusercontent.com/670606/80474863-49618580-8948-11ea-9610-b31b06a9e746.png)

mstsc SUT screenshot:
![image](https://user-images.githubusercontent.com/670606/80474921-65652700-8948-11ea-9744-7443114467fa.png)


If the test data is highly compressed this is expected. If not you should probably regenerate the data.

**Comment by sweeetday** [comment] 2020-04-30 04:16
Hi, Norbert
Thanks for the verification and reporting the issues.
For issue #1, your PR #231 has been merged into the branch. Thanks for the contribution. We have submitted another commit 2d2e264 to include all other pictures into packages too. 
For issue#2, there might some algorithm issues in test data generation algorithm. I need to adjust the algorithm  and keep improving. I will update you then.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by sweeetday** [comment] 2020-05-26 06:38
Hi, Norbert
With investigation and test, I have improved the test data with commit d096f5a. The updated output picture looks like below. Compared with last picture, the quality is improved much. 
However, there is still some light color dislocation. I will keep on improving the test data and update in this thread when there’s better test data generated.
![2](https://user-images.githubusercontent.com/39933478/82868045-7b253680-9f5e-11ea-829b-fdb3a5ddd5f3.jpg)
Thanks.

Best Regards,
Windows Protocol Test Suites Development Team

**Comment by MaggieWang0** [comment] 2021-05-28 07:54
Hi Norbert,
We have improved the test data with commit 71bb807. Below is the new screen shoot of latest output. Please have a try and let us know your feedback.
 
![image](https://user-images.githubusercontent.com/28853205/119933735-3c81ec00-bfb7-11eb-931e-971fdd8defdb.png)

 
Thanks.
 
Best Regards,
Windows Protocol Test Suites Development Team

**Comment by MaggieWang0** [comment] 2021-06-18 06:40
Hi Norbert,

Since this thread has been inactive for a long time, we will close it for now. Please feel free to reopen if the issue still exists.

Best Regards,
Windows Protocol Test Suites Development Team

**Closed** 2021-06-18 08:08 UTC
Labels: RDP, bug
