### ISSUE TITLE
System.NullReferenceException in S6_AutoDetection_ConnectTime_RTT

### ISSUE THREAD

**Issue by ligurio** [microsoft/WindowsProtocolTestSuites#195] opened 2019-07-24 09:01 UTC
```
2019-07-23 10:52:22.585 [Comment] Sending Server Auto-Detect Request PDU with RDP_RTT_REQUEST to SUT

2019-07-23 10:52:22.694 [Comment] Expecting SUT to send a Client Auto-Detect Response PDU

2019-07-23 10:53:02.804 [Comment] Checking the received Client Auto-Detect Response PDU, expect reponseType is RDP_RTT_RESPONSE, and sequenceNumber is 1

2019-07-23 10:53:02.804 [Debug] System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.CheckAutoDetectResponse(NETWORK_DETECTION_RESPONSE autodetectRspPduData, AUTO_DETECT_RESPONSE_TYPE responseType, UInt16 sequenceNumber) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 1977 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.CheckAutoDetectResponsePdu(AUTO_DETECT_RESPONSE_TYPE responseType, UInt16 sequenceNumber) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 1966

2019-07-23 10:53:02.804 [Comment] Trigger client to close all RDP connections for clean up.

2019-07-23 10:53:04.288 [Comment] RDP SUT Control Protocol Adapter: CommandId is 2: error in response: 10.16.171.18:4488, error message:

2019-07-23 10:53:04.288 [Debug] The result of TriggerClientDisconnectAll is -1.

2019-07-23 10:53:04.288 [Comment] Stop RDP listening.
```

Windows Protocol Test Framework 1.0.6000.0
Windows RDP Client Endpoint Test Suite 3.19.3.0

**Comment by huiren-jiang** [comment] 2019-07-26 02:15
Hi Sergey,

Thanks for reporting this issue.

The root cause is this case does not check whether the RTT response PDU is actually received or not. We will fix this soon and notify you in this thread when fix is committed to staging.

Best Regards,

Windows Protocol Test Suites Development Team

**Comment by huiren-jiang** [comment] 2019-07-29 02:07
Hi Sergey,

We fixed this issue by the [commit](https://github.com/microsoft/WindowsProtocolTestSuites/commit/c306ba5bc142c08faa3b07b44880d3a5df219c69) in staging. The series of test cases will now fail with timeout message instead of null exception if no RTT response message is received.

Best Regards,

Windows Protocol Test Suites Development Team

**Closed** 2019-08-13 05:06 UTC
Labels: RDP, bug
